app:
  API:
    airflow_conn_id: out_of_stock
    authorization:
      endpoint: /auth
    data:
      endpoint: /out_of_stock
    headers: 
      content-type: 'application/json'
      Authorization: 'JWT '
    add_params:
  DB:
    airflow_conn_id: my_pg_conn
  HDFS:
    airflow_conn_id: my_hdfs_conn
    partitions:
      orders: order_date
      out_of_stock: date